### ISSUE TITLE
POST API allows for duplicate ids in the post data

### ISSUE THREAD

**Issue by ghost** [roger-maddocks/toDoList#3]
when i post this data twice in a row, it creates two resources both with the id `id2`:
```json
{
	"id": "id2",
	"complete": false,
	"index": 1,
	"thingToDo": "do work"
}
```

I would expect to see the second post fail due to that id already existing. The way the request should fail is the http status code returned from the api call should be `400`

**Comment by roger-maddocks** [comment]
POST API no longer allows for duplicate entries, I have not adjusted the HTTP Response Code yet.

**Comment by roger-maddocks** [comment]
Adjusted HTTP Response code to be 400 when this occurs
