### ISSUE TITLE
GET tasks api does not sort the results by their index

### ISSUE THREAD

**Issue by ghost** [roger-maddocks/toDoList#4]
When this data is returned from the GET api:

```json
[
    {
        "id": "id1",
        "complete": false,
        "index": 1,
        "thingToDo": "do work"
    },
    {
        "id": "id2",
        "complete": false,
        "index": 0,
        "thingToDo": "do more work"
    }
]
```

note that the tasks returned in this json is out of order when considering the `index` field.

i would expect the task w/ id "id2" would be listed first because its "index" is 0.

**Comment by roger-maddocks** [comment]
Functionality has been added to return data in correct order in respect to index
